import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './../styles/Home.module.css'
import React from 'react'
import Contato from './components/Contato'
import Footer from './components/Footer'
import Principal from './components/Principal'
import Servico from './components/Servico'
import SobreNos from './components/SobreNos'
import Header from './components/Header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Contabil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/contabilidade.png" />
      </Head>
      <div>
        <Header></Header>
        <Principal></Principal>
        <SobreNos></SobreNos>
        <Servico></Servico>
        <Contato></Contato>
      </div>
      <Footer></Footer>
    </>
  )
}
